Channel list component & Device list component finished, added test f…
NikoLindborg/Iot-Device-Manager pull request #37
Opened 2022-04-04 16:50 UTC by aleksikyto

…iles, but for now not much to test

2022-04-04 16:59 UTC, NikoLindborg commented on front-end/src/App.tsx
> +import { MqttClient } from 'mqtt'
This can safely be removed from now on

2022-04-04 17:58 UTC, aleksikosonen commented on front-end/src/components/DeviceListComponent/DeviceListComponent.tsx
> +          <h2 className="device-list-label">{componentItems.label}</h2>
I would reconsider these class names, as these should be classes for DeicveListComponents. Could be confusing as we most likely will have a DeviceList in our application, which caption could be misunderstood for 'device-list-label' for example.

2022-04-04 18:00 UTC, aleksikosonen commented on front-end/src/components/ChannelListComponent/ChannelListComponent.tsx
> +      <div className="channel-list-right">
Would rename these to channel-list-component-etc. Same reason as in DeviceListComponent

2022-04-04 18:02 UTC, aleksikosonen requested changes
After the commented fixes this will be great. Awesome job!

2022-04-05 11:34 UTC, aleksikosonen approved these changes
Looks good!

2022-04-05 11:35 UTC, aleksikyto commented on front-end/src/App.tsx
> +const iconPath = process.env.PUBLIC_URL + '/icons/'
Fixed in the latest commit.

2022-04-05 11:35 UTC, aleksikyto commented on front-end/src/components/DeviceListComponent/DeviceListComponent.tsx
> +          <h2 className="device-list-label">{componentItems.label}</h2>
Fixed in the latest commit.

2022-04-05 11:35 UTC, aleksikyto commented on front-end/src/components/ChannelListComponent/ChannelListComponent.tsx
> +      <div className="channel-list-right">
Fixed in the latest commit.

2022-04-05 11:35 UTC, aleksikyto commented on front-end/src/App.tsx
> +import { MqttClient } from 'mqtt'
Fixed in the latest commit.

2022-04-05 11:39 UTC, NikoLindborg approved these changes
looks good to me

2022-04-05 11:40 UTC, merged