Be/mongo mqtt callbacks
NikoLindborg/Iot-Device-Manager pull request #55
Opened 2022-04-13 19:04 UTC by NikoLindborg

#52 Fixed some of the mqtt callbacks to work better now, refactored the entire backend to be more legible, made the websocket update the frontends device list  when a new device announces itself

2022-04-13 19:58 UTC, jaanikaukonen requested changes
Left few comments, other than those, looks fine to me.

2022-04-13 19:58 UTC, jaanikaukonen commented on back-end/src/mqtt/mqtt.ts
> +  const dbTobics = async () => {
```suggestion
  const dbTopics = async () => {
```

2022-04-13 19:58 UTC, jaanikaukonen commented on back-end/src/types/deviceSensorType.ts
> +  sensorData?: [
Why can't we use `ISensorData[]` as a type?

2022-04-13 19:58 UTC, jaanikaukonen commented on back-end/src/mqtt/mqttServices.ts
> +  Device.find({_id: message._id}, (err, docs) => {
We should make own file for mongo functions because now we are repeating code in multiple places. It's should've been done in api endpoints pr now when I think about it.

2022-04-14 04:59 UTC, NikoLindborg commented on back-end/src/types/deviceSensorType.ts
> +  sensorData?: [
For whatever reason, ts linter doesn't like it. Dont know why

2022-04-14 05:27 UTC, NikoLindborg commented on back-end/src/mqtt/mqttServices.ts
> +  Device.find({_id: message._id}, (err, docs) => {
Yeah thats true. Could be added to a ticket in the upcoming sprint

2022-04-14 05:47 UTC, jaanikaukonen commented on back-end/src/types/deviceSensorType.ts
> +  sensorData?: [
Try `import type {ISensorData} from ...` if it makes any difference.

2022-04-14 06:03 UTC, aleksikyto approved these changes
LGTM

2022-04-14 06:05 UTC, aleksikosonen approved these changes
Looks good to me

2022-04-14 06:12 UTC, merged