Added fixes to homeview, added DropDown and used device data in statu…
NikoLindborg/Iot-Device-Manager pull request #56
Opened 2022-04-14 12:53 UTC by aleksikosonen

fixes #18 

## Description

Added a `DropDown` component to select between the broadcasted Channels and filter the `DeviceList` based on it. Also enhanced layout, used devices `trustedState` as data in `StatusComponent` and refactored the DeviceList out of BaseView.

## Added components
- DropDownComponent
- DeviceListComponent

## Additional 
- The DetailsView needs to be though out again, as it should not re-render the `BaseView` components. That's why one StatusComponent is commented out with a comment regarding this.

2022-04-15 06:09 UTC, aleksikosonen commented
Realized the new components are missing Cypress tests so converted PR to Draft and will add them.

2022-04-15 08:01 UTC, aleksikosonen commented
Agreed with @jaanikaukonen that the dropdown should be styled a bit more before merge. Will do that later this weekend

2022-04-15 08:05 UTC, jaanikaukonen commented on front-end/src/components/DropDownComponent/DropDown.tsx
> +  }
```suggestion
  const handleClick = () => {
      setIsDropDownOpen(!isDropDownOpen)
  }
```

2022-04-15 16:03 UTC, NikoLindborg reviewed
Aside from the 1 comment looks good. If your going to be working on this branch more anyways, could include that change aswell

2022-04-15 16:03 UTC, NikoLindborg commented on front-end/src/views/base/BaseView.tsx
> +  })
We should just make an endpoint in the backend that provides channels from databases subscribed channels list with the announcement channel filtered instead of this

2022-04-16 18:03 UTC, aleksikosonen commented on front-end/src/components/DropDownComponent/DropDown.tsx
> +  }
Fixed this in the new commit!

2022-04-16 18:04 UTC, aleksikosonen commented on front-end/src/views/base/BaseView.tsx
> +  })
Done initially this way to reduce database requests, could later on be done that way also if needed

2022-04-16 18:10 UTC, aleksikosonen commented
## Description

Added UI to DropDowns and polished some things on the way. Also added logic to have multiple dropdowns and now devices can be filtered by devices status and subscribed channels. 

# Additional changes

- Changed the trusted values from 0, 1 & 2 to 1, 2 & 3 throughout the code and MongoDB to ease filtering (0 caused issues in filtering)

2022-04-16 18:50 UTC, NikoLindborg commented on front-end/src/views/base/BaseView.tsx
> +  })
1 database request is way smaller problem than having code that gets rerun for no reason on every re-render that the component gets. Uncontrolled code inside a component is not a good idea, or a habit.

2022-04-16 19:05 UTC, NikoLindborg requested changes
Please do the changes requested above

2022-04-17 08:06 UTC, jaanikaukonen commented on front-end/src/components/DropDownComponent/DropDown.tsx
> +        {elements.map((e, i) => (
```suggestion
        {elements.map((element, index) => (
```
Less cryptic imo.

2022-04-17 08:11 UTC, jaanikaukonen commented on front-end/src/views/details/DetailsView.tsx
> +                key={device._id as number}
Does this refer the object id in MongoDb? In mongo, _id is an object, but it can be refer as string. Definitely not a number since it contains characters.

2022-04-17 08:12 UTC, jaanikaukonen commented on front-end/src/components/DropDownComponent/DropDown.tsx
> +  selectedElement: String
```suggestion
  elements: string[]
  selectedElement: string
```
String is JavaScript type for string,
string is TypeScript type for string.

2022-04-17 08:15 UTC, jaanikaukonen requested changes
Update pr description. There are changes in the backend as well, like added cors policy and so on. It is also missing status dropdown, no mention that device card is now wider than before. Also since we found a bug from the dropdown (they overlap if both are open), submit a bug item and put the link to the issue in the desc as well.

Other than those and open comments, looks good!

2022-04-17 08:23 UTC, aleksikosonen commented on front-end/src/components/DropDownComponent/DropDown.tsx
> +        {elements.map((e, i) => (
fixed in the next commit

2022-04-17 08:27 UTC, aleksikosonen commented on front-end/src/components/DropDownComponent/DropDown.tsx
> +  selectedElement: String
fixed in the next commit

2022-04-17 16:06 UTC, aleksikosonen commented on front-end/src/views/base/BaseView.tsx
> +  })
Fixed this in the new commit, added useChannels to ApiHooks

2022-04-17 16:06 UTC, aleksikosonen commented on front-end/src/views/details/DetailsView.tsx
> +                key={device._id as number}
Fixed in the new commit

2022-04-17 16:27 UTC, NikoLindborg approved these changes
Looks good to me now

2022-04-17 16:46 UTC, jaanikaukonen approved these changes

2022-04-17 16:49 UTC, merged