Mongo enhancement for sensor data.
NikoLindborg/Iot-Device-Manager pull request #58
Opened 2022-04-17 14:58 UTC by jaanikaukonen

### Description
`SensorData` is now pushed in own table in `MongoDB`.

###

2022-04-17 16:24 UTC, NikoLindborg approved these changes
looks exactly like we discussed

2022-04-18 07:22 UTC, aleksikosonen commented on back-end/src/schemas/sensorData.ts
> +const sensorDataSchema = new Schema<ISensorData>({
The `sensorDataSchema` should be renamed to `SensorDataSchema` due to the pipeline being case sensitive.

2022-04-18 07:25 UTC, aleksikosonen requested changes
Apart from that one renaming I commented these changes look good.

2022-04-18 08:42 UTC, jaanikaukonen commented on back-end/src/schemas/sensorData.ts
> +const sensorDataSchema = new Schema<ISensorData>({
Fixed.

2022-04-18 08:49 UTC, aleksikosonen approved these changes

2022-04-18 08:56 UTC, merged